services:
  bot:
    image: olegbal/stellar-pp-java-bot:latest
    container_name: pp-bot
    env_file:
      - bot.env
    ports:
      - "8080:8080"
      - "9010:9010"
    restart: always
#  grafana:
#    image: grafana/grafana-oss:latest
#    ports:
#      - "3000:3000"
#    container_name: grafana-monitoring