# List of horizons comma separated. Example:  https://horizon.stellar.org, https://stellarterm.com/horizon
stellar:
  horizons: ${STELLAR_HORIZONS}

logging:
  file:
    path: ./
    name: "server.log"