# List of horizons comma separated. Example:  https://horizon.stellar.org, https://stellarterm.com/horizon
stellar:
  horizons: ${STELLAR_HORIZONS:https://horizon.stellar.org}

payment:
  profit-percent: ${BOT_PROFIT_PERCENTAGE:5}
  base-fee: ${STELLAR_BASE_FEE:1000}

logging:
  file:
    path: ./
    name: "server.log"